package me.tracker.db.jpa.entities;

// Generated Mar 16, 2013 1:31:01 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.GenericGenerator;

/**
 * Price generated by hbm2java
 */
@Entity
@Table(name = "price", catalog = "mydb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"time", "symbol" }))
@Cacheable
@XmlRootElement
public class Price implements java.io.Serializable {

	@Override
	public String toString() {
		return "Price [id=" + id + ", symbol=" + symbol + ", time=" + time
				+ ", bid=" + bid + ", vol=" + vol + ", ask=" + ask + ", mid="
				+ mid + "]";
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 5989471557650921872L;
	private String id;
	private String symbol;
	private Date time;
	private BigDecimal bid;
	private BigDecimal vol;
	private BigDecimal ask;
	private BigDecimal mid;

	public Price() {
	}

	public Price(String id) {
		this.id = id;
	}

	public Price(String id, String symbol, Date time, BigDecimal bid,
			BigDecimal vol, BigDecimal ask, BigDecimal mid) {
		this.id = id;
		this.symbol = symbol;
		this.time = time;
		this.bid = bid;
		this.vol = vol;
		this.ask = ask;
		this.mid = mid;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 45)
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "symbol", length = 20)
	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "bid", precision = 15, scale = 4)
	public BigDecimal getBid() {
		return this.bid;
	}

	public void setBid(BigDecimal bid) {
		this.bid = bid;
	}

	@Column(name = "vol", precision = 15, scale = 4)
	public BigDecimal getVol() {
		return this.vol;
	}

	public void setVol(BigDecimal vol) {
		this.vol = vol;
	}

	@Column(name = "ask", precision = 15, scale = 4)
	public BigDecimal getAsk() {
		return this.ask;
	}

	public void setAsk(BigDecimal ask) {
		this.ask = ask;
	}

	@Column(name = "mid", precision = 15, scale = 4)
	public BigDecimal getMid() {
		return this.mid;
	}

	public void setMid(BigDecimal mid) {
		this.mid = mid;
	}

}
